# Use a lightweight Node.js 20 image
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json and lockfile (if any)
COPY package*.json yarn*.json ./

# Install dependencies using yarn
RUN npm install -g yarn
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose port for development server
EXPOSE 3000

# Start the Next.js development server
CMD [ "yarn", "dev" ]
