#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Define lint-staged commands
npx lint-staged

# Add other checks, e.g., type checking and tests
# Example with TypeScript and Jest:
# npx tsc --noEmit
# npx jest